added form prop to the button component
seas-computing/mark-one pull request #133
Opened 2022-06-07 13:52 UTC by sonusindhu

## Describe your changes
Hello Team,
this PR is related to the bug for #132 
 
I have added 'form' prop to the Button Component to bind that button with the specific form.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality
      to change)

## Checklist:
- [x] Added optional 'form' prop to ButtonProps interface
- [x] Get 'form' from Button Component props 
- [x] Bind 'form' prop to the Button
- [x] I have run `eslint` on the code
- [x] I have added JSDoc for all of my code (where applicable)
- [ ] I have added tests to cover my changes.

## Priority:
- [x] Normal 
- [ ] High 

## Related Issues:

Fixes #132

2022-06-07 19:32 UTC, rmainseas requested changes
This is looking great - thanks for the PR! Would you mind adding an example to [the buttons page](https://github.com/seas-computing/mark-one/blob/main/examples/Buttons/Button.md) to demonstrate this new prop, so we can get this approved and merged?

2022-06-08 13:15 UTC, sonusindhu commented
thanks for the quick review @rmainseas 
I have updated with the example.

2022-06-10 19:05 UTC, rmainseas requested changes
Thanks for adding that! Just a few notes regarding the code snippet.

2022-06-10 19:05 UTC, rmainseas commented on examples/Buttons/Button.md
> +    document.getElementById("name").focus();
This comment is made (somewhat) irrelevant by the on below regarding resetting form state, but I did want to just quickly write a note here to say that dropping to the native DOM API can cause odd issues between component re-renders.

The recommended way to do this tends to be to use a `useRef` hook and then pass the ref to the thing you wish to focus via the `forwardRef` prop. Then call `myRefName.current.focus()` in your handler to focus the element the ref is attached to.

You can see how to focus a `TextInput` with `useRef` [here](https://seas-computing.github.io/mark-one/#/Forms?id=textinput).

2022-06-11 17:12 UTC, sonusindhu commented on examples/Buttons/Button.md
> +      <Button form="simpleForm">Submit</Button>
@rmainseas we already invoked `handleSumit` on form's `onSubmit` event, do you think, we should add on button's `onClick`?

2022-06-13 20:08 UTC, rmainseas commented on examples/Buttons/Button.md
> +      <Button form="simpleForm">Submit</Button>
@sonusindhu a fair point - it is somewhat redundant. However, the `Button` component requires the `onClick` prop. Personally, what I'd probably do is get rid of the `onSubmit` and just keep the `onClick` like you did here.

2022-06-15 15:48 UTC, rmainseas approved these changes
This looks great, thanks for the PR @sonusindhu! I'm going to go ahead and merge this.

2022-06-15 15:48 UTC, merged

2022-06-15 16:06 UTC, sonusindhu commented
thanks @rmainseas, looking forward to the more contribution.