Add Stat Component
seas-computing/mark-one pull request #191
Opened 2024-08-20 15:28 UTC by amalyam

## Describe your changes
This PR adds a `Stat` component which styles inline text representing data or statistics in a monospace font.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality
      to change)

## Checklist:
- [x] I have run `eslint` on the code
- [x] I have added JSDoc for all of my code (where applicable)
- [ ] I have added tests to cover my changes.

## Priority:
- [x] Normal
- [ ] High

## Related Issues:
Closes #186

2024-08-20 18:17 UTC, jonseitz requested changes
Nice work! I have Just a couple things on the component, and then a suggestion for adding a little more context to the documentation with a real usage example.

2024-08-20 18:35 UTC, amalyam commented on src/Typography/Stat.tsx
> +  font-family: ${({ theme }): string => theme.font.data.family};
Got it, I wasn't sure if we wanted more user control over that or not!

2024-08-20 20:46 UTC, amalyam commented on examples/Typography/Stat.md
> + ```
Thanks for laying this all out! Happy to take care of something like this next time!

2024-08-21 13:53 UTC, jonseitz commented on src/Typography/Stat.tsx
> +  font-family: ${({ theme }): string => theme.font.data.family};
Yeah, that makes sense. Maybe not the exact same thing, but Styled Components does have a way to [extend styles][exsty] by wrapping existing components in `styled()` and applying new CSS props.


[exsty]: https://styled-components.com/docs/basics#extending-styles

2024-08-21 13:54 UTC, jonseitz approved these changes
This is all set! :rocket:

2024-08-21 13:59 UTC, amalyam commented on src/Typography/Stat.tsx
> +  font-family: ${({ theme }): string => theme.font.data.family};
Ah ok, good to know!

2024-08-21 13:59 UTC, merged