adding hideError to the Dropdown , and fix the comments and examples …
seas-computing/mark-one pull request #78
Opened 2020-11-03 19:40 UTC by farassadek

1. Add  hideError prop to the Dropdown component 
a. Add example in Dropdown.md
b. Testing
c. Linting

2) Fix the comment in the InputLabel about the hideError prop. 

3) Fix the hideError example  in the TextInput.md

2020-11-03 20:01 UTC, jonseitz requested changes
Just some notes on the tests, mainly about preferring the `testing-library` queries over the `document` methods

2020-11-04 15:27 UTC, farassadek commented on src/Forms/__tests__/Dropdown.test.tsx
> +    });
Good to know that  `window.getComputedStyle` is unreliable. Will remove this.

2020-11-04 16:51 UTC, farassadek commented on src/Forms/__tests__/Dropdown.test.tsx
> +      }));
I prefer to use  `getByRole('combobox')` to be consistent with the tests in the same module since  `getAllByRole('option')` will returns a list.

2020-11-04 18:43 UTC, jonseitz approved these changes
Looks good!

2020-11-04 18:44 UTC, merged